"""Initial schema: providers, harness profiles, variants, experiments, task cards, sessions, requests, rollups, artifacts

Revision ID: 03e22a58f3a7
Revises: 
Create Date: 2026-03-26 07:36:03.280384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e22a58f3a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('harness_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('protocol_surface', sa.String(length=50), nullable=False),
    sa.Column('base_url_env', sa.String(length=255), nullable=False),
    sa.Column('api_key_env', sa.String(length=255), nullable=False),
    sa.Column('model_env', sa.String(length=255), nullable=False),
    sa.Column('extra_env', sa.JSON(), nullable=False),
    sa.Column('render_format', sa.String(length=20), nullable=False),
    sa.Column('launch_checks', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('route_name', sa.String(length=255), nullable=True),
    sa.Column('protocol_surface', sa.String(length=50), nullable=False),
    sa.Column('upstream_base_url_env', sa.String(length=255), nullable=False),
    sa.Column('api_key_env', sa.String(length=255), nullable=False),
    sa.Column('routing_defaults', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rollups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dimension_type', sa.String(length=50), nullable=False),
    sa.Column('dimension_id', sa.String(length=255), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rollups_dimension_id'), 'rollups', ['dimension_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.String(length=255), nullable=False),
    sa.Column('variant_id', sa.String(length=255), nullable=False),
    sa.Column('task_card_id', sa.String(length=255), nullable=False),
    sa.Column('harness_profile', sa.String(length=255), nullable=False),
    sa.Column('repo_path', sa.String(length=1024), nullable=False),
    sa.Column('git_branch', sa.String(length=255), nullable=False),
    sa.Column('git_commit', sa.String(length=64), nullable=False),
    sa.Column('git_dirty', sa.Boolean(), nullable=False),
    sa.Column('operator_label', sa.String(length=255), nullable=True),
    sa.Column('proxy_credential_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('repo_path', sa.String(length=1024), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('starting_prompt', sa.Text(), nullable=False),
    sa.Column('stop_condition', sa.Text(), nullable=False),
    sa.Column('session_timebox_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('provider_route', sa.String(length=255), nullable=True),
    sa.Column('model_alias', sa.String(length=255), nullable=False),
    sa.Column('harness_profile', sa.String(length=255), nullable=False),
    sa.Column('harness_env_overrides', sa.JSON(), nullable=False),
    sa.Column('benchmark_tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=2048), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('artifact_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_session_id'), 'artifacts', ['session_id'], unique=False)
    op.create_table('experiment_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('variant_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('upstream_model', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('ttft_ms', sa.Float(), nullable=True),
    sa.Column('tokens_prompt', sa.Integer(), nullable=True),
    sa.Column('tokens_completion', sa.Integer(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_request_id'), 'requests', ['request_id'], unique=False)
    op.create_index(op.f('ix_requests_session_id'), 'requests', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_session_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_request_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_table('provider_models')
    op.drop_table('experiment_variants')
    op.drop_index(op.f('ix_artifacts_session_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('variants')
    op.drop_table('task_cards')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_rollups_dimension_id'), table_name='rollups')
    op.drop_table('rollups')
    op.drop_table('providers')
    op.drop_table('harness_profiles')
    op.drop_table('experiments')
    # ### end Alembic commands ###
