apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      httpMethod: "POST"
    healthCheck:
      interval: "10s"
      enabled: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: stackperf
    user: stackperf
    editable: false
    jsonData:
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: stackperf-dev-password
