apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://litellm-prometheus:9090
    isDefault: true
    editable: false
    uid: prometheus-datasource
    jsonData:
      timeInterval: 5s
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      cacheLevel: 'High'
    secureJsonData: {}

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    editable: false
    uid: postgres-datasource
    jsonData:
      postgresVersion: 1600
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
