apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://litellm-prometheus:9090
    isDefault: true
    editable: false
    uid: prometheus-datasource
    jsonData:
      timeInterval: 5s
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      cacheLevel: 'High'
    secureJsonData: {}
