model_list: []

litellm_settings:
  drop_params: True
  num_retries: 3
  request_timeout: 600
  callbacks: ["prometheus"]

router_settings:
  routing_strategy: simple-shuffle
  num_retries: 3
  timeout: 30
  allowed_fails: 3
  cooldown_time: 10

prometheus:
  enabled: True
  verbose: False
